<?php header('Content-type: application/json; charset: utf8');

switch($_REQUEST['a']){
	case "menu":
		$answer = array(
			"status"=>true,
			"message"=>"Ок",
			"structure"=>array(
				array(
					'type'=>"menu",
					'class'=>"b-dynamic-menu_amtel",
					'place'=>".b-dynamic-menu",
					'items'=>array(
						array(
							"title"=>"клиенты",
							"description"=>"",
							"action"=>"client"
						),
						array(
							"title"=>"агенты",
							"description"=>"",
							"action"=>"agent"
						),
						array(
							"title"=>"спутники",
							"description"=>"",
							"action"=>"satellist"
						),
						array(
							"title"=>"станции",
							"description"=>"",
							"action"=>"station"
						),
						array(
							"title"=>"1С",
							"description"=>"",
							"action"=>"one_s"
						),
						array(
							"title"=>"статистика",
							"description"=>"",
							"action"=>"statistic"
						),
						array(
							"title"=>"плат.карты",
							"description"=>"",
							"action"=>"cardgen"
						),
						array(
							"title"=>"тарифы",
							"description"=>"",
							"action"=>"tarifs"
						)
					)//items
				)//menu
			)//structure
		);
	break;
	case "client":
		echo '{
			"status":true,
			"message":"Ok",
			"structure":[
			  {
				"type":"form",
				"name":"clients",
				"action":"?",
				"method":"POST",
				"content":{
				  "text":{
					"name":"login",
					"label":"Логин",
					"value":"Вася"
				  },
				  "password":{
					"name":"password",
					"label":"Пароль",
					"value":"123"
				  },
				  "check":{
					"name":"remember_me",
					"label":"Запомнить меня",
					"value":"checked"
				  },
				  "option":{
					"name":"permissions",
					"label":"Как пользователь",
					"value":"checked"
				  },
				  "option":{
					"name":"permissions",
					"label":"Как администратор",
					"value":""
				  },
				  "list":{
					"name":"modules",
					"label":"Доступные модули",
					"options":[
					  {
						"label":"Клиенты",
						"value":"clients",
						"selected":"selected"
					  },
					  {
						"label":"Группы",
						"value":"groups",
						"selected":"selected"
					  },
					  {
						"label":"Тарифы",
						"value":"tariffs"
					  },
					  {
						"label":"Отчёты",
						"value":"reports",
						"disabled":"disabled"
					  },
					  {
						"label":"Настройки",
						"value":"settings",
						"selected":"selected"
					  }
					]
				  },
				  "combo":{
					"name":"server",
					"label":"Сервер для входа",
					"options":[
					  {
						"label":"Москва",
						"value":"192.168.1.1"
					  },
					  {
						"label":"Барнаул",
						"value":"192.168.1.2"
					  },
					  {
						"label":"Петропавловск-Камчатский",
						"value":"192.168.1.3",
						"disabled":"disabled"
					  },
					  {
						"label":"Тест",
						"value":"192.168.1.4",
						"selected":"selected"
					  }
					]
				  },
				  "submit":{
					"value":"Войти"
				  }
				}
			  }
			]
		  }';
		
	break;
	
	default:
		$answer = array(
			"status"=>true,
			"message"=>"Ок",
			"structure"=>array(
				array(
					'type'=>"menu",
					'class'=>"b-menu_amtel",
					'place'=>".b-dynamic-menu",
					'items'=>array(
						array(
							"title"=>"клиенты",
							"description"=>"",
							"action"=>"client"
						),
						array(
							"title"=>"агенты",
							"description"=>"",
							"action"=>"agent"
						),
						array(
							"title"=>"спутники",
							"description"=>"",
							"action"=>"satellist"
						),
						array(
							"title"=>"станции",
							"description"=>"",
							"action"=>"station"
						),
						array(
							"title"=>"1С",
							"description"=>"",
							"action"=>"one_s"
						),
						array(
							"title"=>"статистика",
							"description"=>"",
							"action"=>"statistic"
						),
						array(
							"title"=>"плат.карты",
							"description"=>"",
							"action"=>"cardgen"
						),
						array(
							"title"=>"тарифы",
							"description"=>"",
							"action"=>"tarifs"
						)
					)//items
				)//menu
			)//structure
		);
	break;

}

if($answer){echo json_encode($answer);}
?>