<?php ?>
{
	"status":true,
	"message":"Ok",
	"structure":{
		"menu":[
		  {
			"description":"клиенты",
			"action":"client"
		  },
		  {
			"description":"агенты",
			"action":"agent"
		  },
		  {
			"description":"спутники",
			"action":"satellist"
		  },
		  {
			"description":"станции",
			"action":"station"
		  },
		  {
			"description":"1С",
			"action":"one_s"
		  },
		  {
			"description":"статистика",
			"action":"statistic"
		  },
		  {
			"description":"плат.карты",
			"action":"cardgen"
		  },
		  {
			"description":"тарифы",
			"action":"tarifs"
		  }
		]
	}
}
<?php ?>